### ISSUE TITLE
Identify the composition of the "CoC team" with address `report@bytecodealliance.org`

### ISSUE THREAD

**Issue by Kylebrown9** [bytecodealliance/governance#33]
Code of Conduct document identifies that reports will be handled by this team but does not identify who makes it up. Is this handled by David Bryant who is identified as the Compliance Officer in the Whistleblower Policy or someone else?

**Comment by disquisitioner** [comment]
This issue was resolved in an update to the TSC Charter as part of [June 2023 TSC Governance Update (#38)](https://github.com/bytecodealliance/governance/pull/38).
