### ISSUE TITLE
Proposal to create `wac`

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/governance#82]
# Proposal to Create `wac`

This document is a proposal to create `wac` as a formal Hosted Project under the auspices of the TSC of the Bytecode Alliance, as specified in the [TSC Charter].

## Project Summary

`wac` is a tool for defining WebAssembly compositions from a formally defined language called WebAssembly Compositions.

It is a successor to the existing Bytecode Alliance tool `wasm-compose`.

The main justification for having `wac` as a stand-alone project compared to integrating it directly into `wasm-tools` is that it will have a direct build dependency on `wasmtime` to support the execution of arbitrarily-referenced "transform" plugins.

### Existing Resources

- [GitHub repository](https://github.com/peterhuene/wac)

## Governance Summary

This project will begin with the current maintainers of the `wac` project and add additional maintainers from Bytecode Alliance member organizations over time; the representation of multiple organizations (and potentially within the Component Model proposal itself with respect to the language's design) will be an important aspect of this project.

## Software Development Process

All code changes will be required to go through a pull request with at least one approval by a maintainer and passing all CI checks.

Code quality will be maintained through the CI process, including the eventual support for fuzzing the `wac` parser and encoder.

Releases will be performed similarly to existing BA repositories, where the creation of a tag will automate the publishing of the release to `crates.io`.

## Alignment with Bytecode Alliance Mission and Goals

Bytecode Alliance projects represent the mission and goals of the Bytecode Alliance itself.
We understand that as a Bytecode Alliance project, our project must adhere to the [TSC Charter] and other governing documents (such as the [Security Policies] and [IP Policy]).
As a Bytecode Alliance project, our project's source code and other pieces of intellectual property will be assigned to the Bytecode Alliance.

We understand and agree that:

- All code for this project must be under the [Apache v2 License with the LLVM exception](/PROJECT_LICENSE), unless an exception is required for compliance with existing licensing, and granted by the Bytecode Alliance's board of directors per [IP Policy] §4. If our code is not already licenses accordingly, we will take the necessary steps to correct this prior to becoming a Bytecode Alliance Project.
- We will comply with the [Security Policies].
- Project name, trademarks, logos, wordmarks, and other intellectual property other than source code and documentation copyright is assigned to Bytecode Alliance per the [IP Policy].
- Social media handles, GitHub repository access, and other relevant communication and coordination platforms will be overseen by Bytecode Alliance. Administrative/Owner permissions will be granted to the Bytecode Alliance for all such accounts.
- We will abide by the definition of a project as set forth in the [TSC Charter].
- This project must remain under active development or maintenance, or it may be archived by the Bytecode Alliance.
- This project may be reviewed from time to time by the TSC, and project maintainers will assist with this review process.
- Project members will be able to participate in Bytecode Alliance governance, as specified in the [TSC Charter] and other governing documents.

## Supporting Members 

The following individuals support the creation of `wac`:

- Brian Hardock (Fermyon)
- Danny Macovei (JAF Labs)
- L Pereira (Fastly)
- Luke Wagner (Fastly)
- Peter Huene (Fastly)
- Ryan Levick (Fermyon)
- Trevor Elliott (Fastly)

[Security Policies]: https://bytecodealliance.org/security
[TSC Charter]: https://github.com/bytecodealliance/governance/blob/main/TSC/charter.md
[IP Policy]: https://bytecodealliance.org/assets/ip-policy.pdf

**Comment by ricochet** [comment]
The TSC has reviewed this proposal, and I am happy to say that it was approved!  Please initiate the transfer the Bytecode Alliance and I will work with you to ensure it meets all of the above Bytecode Alliance policies. Thank you!

**Comment by ricochet** [comment]
Project has been transferred and is now available at https://github.com/bytecodealliance/wac
