### ISSUE TITLE
Proposal to Create rust-oci-wasm

### ISSUE THREAD

**Issue by thomastaylor312** [bytecodealliance/governance#88]
This issue is a proposal to create the rust-oci-wasm crate as a formal hosted project under the auspices of the TSC of the Bytecode Alliance, as specified in the TSC Charter.

## Project summary

Now that there has been general agreement on [the spec for components in OCI artifacts](https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/), we needed to create some implementations that can be used to leverage the new types (such as `wasm-pkg-tools`). After consulting with various groups, the best home seems to be here in the BCA. This proposes that the https://github.com/thomastaylor312/rust-oci-wasm repo be transferred into the `bytecodealliance` org as a new project. This project will remain separate for some time as the contributors to this will span both active CNCF contributors and BCA contributors, so it will be easier to keep it separate for now for those who wouldn't be maintainers of `wasm-pkg-tools`. This doesn't preclude us from merging into that project in the future, but for now it would probably be best as a separate repo.

This is part of a cross community effort (special shout out to @jsturtevant) and was also discussed as part of SIG Registry on May 22: https://hackmd.io/9FXZK5TxSwSU-5mHNbFGBQ#May-22---SIG-Registries-meeting. 

### Additional resources

- [OCI Wasm Spec](https://tag-runtime.cncf.io/wgs/wasm/deliverables/wasm-oci-artifact/)
- https://github.com/thomastaylor312/rust-oci-wasm
- [Discussion in CNCF Wasm WG](https://docs.google.com/document/d/1d6PvdCuKbSdcuXG2M9fBSDQPTPfHYA0PPDTM2plbH3I/edit) (see May 28th meeting)
- [Discussion in BCA SIG registry](https://hackmd.io/9FXZK5TxSwSU-5mHNbFGBQ#May-22---SIG-Registries-meeting)

## Supporting members

The following individuals support the creation of this project:

- @thomastaylor312 
- @calvinrp 
- @jsturtevant

Please also note the general support of the members of the SIG registry and CNCF wasm working group

**Comment by ricochet** [comment]
The TSC discussed this issue today and are excited about this work! Will you please run through our proposed [hosted project requirements](https://github.com/bytecodealliance/governance/pull/52/files#diff-12a7928875c9aa9397d6ee49345005fc778d716312c874882877f3bd04f9a799) and align your project with the Bytecode Alliance requirements? One that we noticed for example is that the license should be Apache 2.0 with the LLVM exception. Thank you!

**Comment by thomastaylor312** [comment]
I'll get that going now!

**Comment by thomastaylor312** [comment]
Ok, I have updated the repository with the new license and have documented everything from the project requirements in the recent PR I merged to the project.

The only thing I haven't done yet is add a specific group to Crates.io with pushing rights. I will do this as soon as we move over to the BCA so we can have a "rust-oci-maintainers" group that I can add to crates.io

**Comment by ricochet** [comment]
The TSC has reviewed this proposal, and I am happy to say that it was approved! Please initiate the transfer to the Bytecode Alliance. Thank you!

**Comment by thomastaylor312** [comment]
This has been completed https://github.com/bytecodealliance/rust-oci-wasm. Thanks all!
